-- 方案管理相关表

CREATE TABLE IF NOT EXISTS `biz_plan` (
  `plan_id` bigint NOT NULL AUTO_INCREMENT,
  `plan_no` varchar(30) NOT NULL COMMENT '方案编号',
  `enterprise_id` bigint NOT NULL COMMENT '企业ID',
  `plan_name` varchar(100) NOT NULL COMMENT '方案名称',
  `commission_rate` decimal(5,2) DEFAULT 0 COMMENT '分成比例(%)',
  `plan_amount` decimal(12,2) DEFAULT 0 COMMENT '方案金额(店家付款)',
  `gift_amount` decimal(12,2) DEFAULT 0 COMMENT '配赠金额',
  `shipped_amount` decimal(12,2) DEFAULT 0 COMMENT '已出金额',
  `remaining_amount` decimal(12,2) DEFAULT 0 COMMENT '剩余金额',
  `effective_date` date DEFAULT NULL COMMENT '生效日期',
  `expiry_date` date DEFAULT NULL COMMENT '失效日期',
  `audit_status` char(1) DEFAULT '0' COMMENT '审核状态(0草稿 1待审核 2已审核 3已完成 4已驳回)',
  `audit_by` varchar(64) DEFAULT NULL COMMENT '审核人',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `audit_remark` varchar(500) DEFAULT NULL COMMENT '审核备注',
  `status` char(1) DEFAULT '0' COMMENT '启用状态(0启用 1停用)',
  `remark` text DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`plan_id`),
  UNIQUE KEY `uk_plan_no` (`plan_no`),
  KEY `idx_enterprise_id` (`enterprise_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='方案表';

CREATE TABLE IF NOT EXISTS `biz_plan_item` (
  `item_id` bigint NOT NULL AUTO_INCREMENT,
  `plan_id` bigint NOT NULL COMMENT '方案ID',
  `product_id` bigint DEFAULT NULL COMMENT '货品ID',
  `product_name` varchar(100) DEFAULT NULL COMMENT '货品名称',
  `supplier_id` bigint DEFAULT NULL COMMENT '供货商ID',
  `supplier_name` varchar(100) DEFAULT NULL COMMENT '供货商名称',
  `unit_type` char(1) DEFAULT '1' COMMENT '单位类型(1主单位整 2副单位拆)',
  `pack_qty` int DEFAULT 1 COMMENT '换算比例',
  `quantity` int DEFAULT 0 COMMENT '数量(最小单位)',
  `spec` varchar(20) DEFAULT NULL COMMENT '规格',
  `sale_price` decimal(10,2) DEFAULT 0 COMMENT '单价',
  `amount` decimal(12,2) DEFAULT 0 COMMENT '总金额',
  `shipped_quantity` int DEFAULT 0 COMMENT '已出数量',
  `remaining_quantity` int DEFAULT 0 COMMENT '剩余数量',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`item_id`),
  KEY `idx_plan_id` (`plan_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='方案配赠明细表';

CREATE TABLE IF NOT EXISTS `biz_shipment` (
  `shipment_id` bigint NOT NULL AUTO_INCREMENT,
  `shipment_no` varchar(30) NOT NULL COMMENT '出货单号',
  `plan_id` bigint NOT NULL COMMENT '关联方案ID',
  `enterprise_id` bigint NOT NULL COMMENT '企业ID',
  `enterprise_name` varchar(100) DEFAULT NULL COMMENT '企业名称',
  `contact_person` varchar(50) DEFAULT NULL COMMENT '收货人',
  `contact_phone` varchar(20) DEFAULT NULL COMMENT '收货电话',
  `shipping_address` varchar(255) DEFAULT NULL COMMENT '收货地址',
  `total_quantity` int DEFAULT 0 COMMENT '总数量',
  `total_amount` decimal(12,2) DEFAULT 0 COMMENT '总金额(折扣后)',
  `logistics_company` varchar(50) DEFAULT NULL COMMENT '物流公司',
  `logistics_no` varchar(50) DEFAULT NULL COMMENT '物流单号',
  `shipment_status` char(1) DEFAULT '0' COMMENT '出货状态(0待审核 1已审核 2已发货 3已收货 4已驳回)',
  `shipment_date` date DEFAULT NULL COMMENT '发货日期',
  `receipt_date` date DEFAULT NULL COMMENT '收货日期',
  `audit_by` varchar(64) DEFAULT NULL COMMENT '审核人',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `remark` text DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`shipment_id`),
  UNIQUE KEY `uk_shipment_no` (`shipment_no`),
  KEY `idx_plan_id` (`plan_id`),
  KEY `idx_enterprise_id` (`enterprise_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='出货单表';

CREATE TABLE IF NOT EXISTS `biz_shipment_item` (
  `item_id` bigint NOT NULL AUTO_INCREMENT,
  `shipment_id` bigint NOT NULL COMMENT '出货单ID',
  `plan_item_id` bigint DEFAULT NULL COMMENT '关联方案明细ID',
  `product_id` bigint DEFAULT NULL COMMENT '货品ID',
  `product_name` varchar(100) DEFAULT NULL COMMENT '货品名称',
  `supplier_id` bigint DEFAULT NULL COMMENT '供货商ID',
  `supplier_name` varchar(100) DEFAULT NULL COMMENT '供货商名称',
  `unit_type` char(1) DEFAULT '1' COMMENT '单位类型(1主单位 2副单位)',
  `pack_qty` int DEFAULT 1 COMMENT '换算比例',
  `quantity` int DEFAULT 0 COMMENT '数量(最小单位)',
  `spec` varchar(20) DEFAULT NULL COMMENT '规格',
  `sale_price` decimal(10,2) DEFAULT 0 COMMENT '单价',
  `discount_price` decimal(10,2) DEFAULT 0 COMMENT '折扣单价',
  `amount` decimal(12,2) DEFAULT 0 COMMENT '总金额(折扣单价×数量)',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`item_id`),
  KEY `idx_shipment_id` (`shipment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='出货明细表';
